--CREATE PROCEDURE urunkategori
--AS
--SELECT TBLKATEGORI.AD , COUNT (TBLURUN.AD)AS 'ADET'
--FROM TBLURUN INNER JOIN TBLKATEGORI
--ON TBLKATEGORI.ID = TBLURUN.KATEGORI
--GROUP BY TBLKATEGORI.AD
--ORDER BY ADET

EXECUTE urunkategori