--CREATE PROCEDURE makskategoriurun
--AS
--SELECT TOP 1 TBLKATEGORI.AD,COUNT(*) FROM TBLURUN
--INNER JOIN TBLKATEGORI ON TBLKATEGORI.ID=TBLURUN.KATEGORI
--GROUP BY TBLKATEGORI.AD ORDER BY COUNT(*) DESC

exec makskategoriurun